import type { AppRole, Permission } from "./types"
import { PERMISSIONS } from "./types"

export const ROLE_LABELS: Record<AppRole, string> = {
  super_admin: "Super Admin",
  admin: "Administrador",
  gerencia: "Gerência",
  comercial: "Comercial",
  operacional: "Operacional",
  financeiro: "Financeiro",
  parceiro: "Parceiro",
  leitura: "Leitura",
  sales: "Comercial",
  broker: "Corretor",
  underwriter: "Subscritor",
  viewer: "Visualizador",
}

const ALL: Permission[] = [...PERMISSIONS]

export const ROLE_PERMISSIONS: Record<AppRole, readonly Permission[]> = {
  super_admin: ALL,
  admin: ALL,
  gerencia: [
    "dashboard:view",
    "crm:view",
    "crm:manage",
    "clients:view",
    "clients:manage",
    "leads:view",
    "leads:manage",
    "leads:share",
    "questionnaires:view",
    "questionnaires:manage",
    "quotes:view",
    "quotes:manage",
    "audit:view",
    "settings:view",
  ],
  comercial: [
    "dashboard:view",
    "crm:view",
    "crm:manage",
    "clients:view",
    "leads:view",
    "leads:manage",
    "leads:share",
    "questionnaires:view",
    "questionnaires:manage",
    "quotes:view",
    "quotes:manage",
    "settings:view",
  ],
  operacional: [
    "dashboard:view",
    "clients:view",
    "clients:manage",
    "leads:view",
    "policies:view",
    "policies:manage",
    "claims:view",
    "claims:manage",
    "questionnaires:view",
    "settings:view",
  ],
  financeiro: [
    "dashboard:view",
    "clients:view",
    "policies:view",
    "audit:view",
    "settings:view",
  ],
  parceiro: ["dashboard:view", "leads:view"],
  leitura: ALL.filter((p) => p.endsWith(":view")),
  sales: ["crm:manage", "leads:manage", "clients:view"],
  broker: [
    "dashboard:view",
    "crm:view",
    "crm:manage",
    "clients:view",
    "clients:manage",
    "leads:view",
    "leads:manage",
    "questionnaires:view",
    "questionnaires:manage",
    "quotes:view",
    "quotes:manage",
    "whatsapp:view",
    "whatsapp:manage",
    "settings:view",
  ],
  underwriter: [
    "dashboard:view",
    "clients:view",
    "quotes:view",
    "quotes:manage",
    "policies:view",
    "policies:manage",
    "claims:view",
    "claims:manage",
    "questionnaires:view",
    "settings:view",
  ],
  viewer: [
    "dashboard:view",
    "crm:view",
    "clients:view",
    "leads:view",
    "questionnaires:view",
    "quotes:view",
    "policies:view",
    "claims:view",
    "whatsapp:view",
    "automation:view",
    "settings:view",
    "audit:view",
  ],
}

export function getPermissionsForRole(role: AppRole): Permission[] {
  return [...(ROLE_PERMISSIONS[role] ?? [])]
}
