import type { LucideIcon } from "lucide-react"
import {
  AlertTriangle,
  Briefcase,
  Building,
  Car,
  CheckSquare,
  Cigarette,
  CreditCard,
  FileText,
  Hash,
  Heart,
  HeartPulse,
  Home,
  IdCard,
  List,
  Mail,
  MapPin,
  Package,
  Phone,
  Shield,
  User,
  Users,
  Video,
  Warehouse,
  Wrench,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  user: User,
  users: Users,
  car: Car,
  "id-card": IdCard,
  building: Building,
  calendar: Hash,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  home: Home,
  "check-square": CheckSquare,
  "credit-card": CreditCard,
  file: FileText,
  hash: Hash,
  warehouse: Warehouse,
  "alert-triangle": AlertTriangle,
  shield: Shield,
  heart: Heart,
  "heart-pulse": HeartPulse,
  cigarette: Cigarette,
  briefcase: Briefcase,
  package: Package,
  video: Video,
  wrench: Wrench,
  list: List,
}

export function resolveLibraryIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? FileText
}
