import type { ValidationRuleV1, ValidationSchemaV1 } from "@repo/forms-engine"
import type { FieldDefinition } from "../metadata/types"

function v1(...rules: ValidationRuleV1[]): ValidationSchemaV1 {
  return { version: 1, rules }
}

function field(partial: FieldDefinition): FieldDefinition {
  return partial
}

export const sharedFields: FieldDefinition[] = [
  field({
    id: "shared.full_name",
    name: "full_name",
    key: "full_name",
    label: "Nome completo",
    description: "Nome completo do segurado ou proponente.",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }, { type: "minLength", value: 3 }),
    category: "dados_pessoais",
    product: "shared",
    tags: ["nome", "pessoal", "identificacao"],
    icon: "user",
    documentation: "Campo padrão para identificação nominal.",
    required: true,
  }),
  field({
    id: "shared.cpf",
    name: "cpf",
    key: "cpf",
    label: "CPF",
    description: "Cadastro de Pessoa Física.",
    inputKind: "cpf",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }, { type: "cpf" }),
    defaultMask: "cpf",
    defaultPlaceholder: "000.000.000-00",
    category: "documentos",
    product: "shared",
    tags: ["cpf", "documento", "pf"],
    icon: "id-card",
    required: true,
  }),
  field({
    id: "shared.cnpj",
    name: "cnpj",
    key: "cnpj",
    label: "CNPJ",
    description: "Cadastro Nacional de Pessoa Jurídica.",
    inputKind: "cnpj",
    fieldType: "TEXT",
    validation: v1({ type: "cnpj" }),
    defaultMask: "cnpj",
    defaultPlaceholder: "00.000.000/0000-00",
    category: "documentos",
    product: "shared",
    tags: ["cnpj", "documento", "pj"],
    icon: "building",
  }),
  field({
    id: "shared.birth_date",
    name: "birth_date",
    key: "birth_date",
    label: "Data de nascimento",
    description: "Data de nascimento para cálculo de risco.",
    inputKind: "date",
    fieldType: "DATE",
    validation: v1({ type: "required", when: "finalize" }),
    defaultPlaceholder: "DD/MM/AAAA",
    category: "dados_pessoais",
    product: "shared",
    tags: ["nascimento", "idade"],
    icon: "calendar",
    required: true,
  }),
  field({
    id: "shared.email",
    name: "email",
    key: "email",
    label: "E-mail",
    description: "E-mail para contato e envio de proposta.",
    inputKind: "email",
    fieldType: "EMAIL",
    validation: v1({ type: "email" }),
    category: "contato",
    product: "shared",
    tags: ["email", "contato"],
    icon: "mail",
  }),
  field({
    id: "shared.phone",
    name: "phone",
    key: "phone",
    label: "Telefone",
    description: "Telefone celular ou fixo.",
    inputKind: "phone",
    fieldType: "PHONE",
    validation: v1({ type: "phone" }),
    defaultMask: "phone",
    defaultPlaceholder: "(00) 00000-0000",
    category: "contato",
    product: "shared",
    tags: ["telefone", "contato"],
    icon: "phone",
  }),
  field({
    id: "shared.cep",
    name: "cep",
    key: "cep",
    label: "CEP",
    description: "CEP do endereço.",
    inputKind: "cep",
    fieldType: "TEXT",
    validation: v1({ type: "cep" }),
    defaultMask: "cep",
    defaultPlaceholder: "00000-000",
    category: "endereco",
    product: "shared",
    tags: ["cep", "endereco"],
    icon: "map-pin",
  }),
  field({
    id: "shared.address",
    name: "address",
    key: "address",
    label: "Endereço",
    description: "Logradouro e número.",
    inputKind: "short_text",
    fieldType: "TEXT",
    category: "endereco",
    product: "shared",
    tags: ["endereco", "logradouro"],
    icon: "home",
  }),
  field({
    id: "shared.yes_no",
    name: "yes_no_generic",
    key: "yes_no",
    label: "Sim/Não",
    description: "Pergunta booleana genérica.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "dados_pessoais",
    product: "shared",
    tags: ["boolean", "sim", "nao"],
    icon: "check-square",
  }),
  field({
    id: "shared.currency",
    name: "currency_value",
    key: "currency_value",
    label: "Valor",
    description: "Valor monetário.",
    inputKind: "currency",
    fieldType: "CURRENCY",
    category: "financeiro",
    product: "shared",
    tags: ["valor", "financeiro"],
    icon: "credit-card",
  }),
  field({
    id: "shared.file_upload",
    name: "file_upload",
    key: "attachment",
    label: "Anexo",
    description: "Upload de documento ou imagem.",
    inputKind: "file",
    fieldType: "FILE",
    validation: v1({ type: "fileRequired" }),
    category: "anexos",
    product: "shared",
    tags: ["arquivo", "anexo"],
    icon: "file",
  }),
]

export const autoFields: FieldDefinition[] = [
  field({
    id: "auto.plate",
    name: "vehicle_plate",
    key: "vehicle_plate",
    label: "Placa",
    description: "Placa do veículo segurado.",
    inputKind: "plate",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }, { type: "plate" }),
    defaultMask: "plate",
    defaultPlaceholder: "ABC1D23",
    category: "veiculos",
    product: "auto",
    tags: ["placa", "veiculo", "auto"],
    icon: "car",
    required: true,
  }),
  field({
    id: "auto.brand",
    name: "vehicle_brand",
    key: "vehicle_brand",
    label: "Marca",
    description: "Marca do veículo.",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }),
    category: "veiculos",
    product: "auto",
    tags: ["marca", "veiculo"],
    icon: "car",
    required: true,
  }),
  field({
    id: "auto.model",
    name: "vehicle_model",
    key: "vehicle_model",
    label: "Modelo",
    description: "Modelo do veículo.",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }),
    category: "veiculos",
    product: "auto",
    tags: ["modelo", "veiculo"],
    icon: "car",
    required: true,
  }),
  field({
    id: "auto.year",
    name: "vehicle_year",
    key: "vehicle_year",
    label: "Ano",
    description: "Ano de fabricação ou modelo.",
    inputKind: "number",
    fieldType: "NUMBER",
    validation: v1({ type: "required", when: "finalize" }, { type: "min", value: 1950 }),
    category: "veiculos",
    product: "auto",
    tags: ["ano", "veiculo"],
    icon: "hash",
    required: true,
  }),
  field({
    id: "auto.chassi",
    name: "vehicle_chassis",
    key: "vehicle_chassis",
    label: "Chassi",
    description: "Número do chassi (17 caracteres).",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "chassi" }),
    defaultPlaceholder: "17 caracteres",
    category: "veiculos",
    product: "auto",
    tags: ["chassi", "veiculo"],
    icon: "car",
  }),
  field({
    id: "auto.renavam",
    name: "vehicle_renavam",
    key: "vehicle_renavam",
    label: "Renavam",
    description: "Registro Nacional de Veículos Automotores.",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "renavam" }),
    category: "veiculos",
    product: "auto",
    tags: ["renavam", "veiculo"],
    icon: "hash",
  }),
  field({
    id: "auto.main_driver_name",
    name: "main_driver_name",
    key: "main_driver_name",
    label: "Nome do condutor principal",
    description: "Nome completo do condutor principal.",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }),
    category: "condutores",
    product: "auto",
    tags: ["condutor", "principal"],
    icon: "user",
    required: true,
  }),
  field({
    id: "auto.main_driver_cpf",
    name: "main_driver_cpf",
    key: "main_driver_cpf",
    label: "CPF do condutor principal",
    description: "CPF do condutor principal.",
    inputKind: "cpf",
    fieldType: "TEXT",
    validation: v1({ type: "cpf" }),
    defaultMask: "cpf",
    category: "condutores",
    product: "auto",
    tags: ["condutor", "cpf"],
    icon: "id-card",
  }),
  field({
    id: "auto.main_driver_license",
    name: "main_driver_license",
    key: "main_driver_license",
    label: "CNH do condutor principal",
    description: "Número da Carteira Nacional de Habilitação.",
    inputKind: "short_text",
    fieldType: "TEXT",
    category: "condutores",
    product: "auto",
    tags: ["cnh", "condutor"],
    icon: "id-card",
  }),
  field({
    id: "auto.has_second_driver",
    name: "has_second_driver",
    key: "has_second_driver",
    label: "Possui segundo condutor?",
    description: "Indica se há um segundo condutor habitual.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "condutores",
    product: "auto",
    tags: ["segundo condutor", "condutor"],
    icon: "users",
  }),
  field({
    id: "auto.second_driver_name",
    name: "second_driver_name",
    key: "second_driver_name",
    label: "Nome do segundo condutor",
    description: "Nome completo do segundo condutor.",
    inputKind: "short_text",
    fieldType: "TEXT",
    category: "condutores",
    product: "auto",
    tags: ["segundo condutor"],
    icon: "user",
  }),
  field({
    id: "auto.second_driver_cpf",
    name: "second_driver_cpf",
    key: "second_driver_cpf",
    label: "CPF do segundo condutor",
    description: "CPF do segundo condutor.",
    inputKind: "cpf",
    fieldType: "TEXT",
    validation: v1({ type: "cpf" }),
    defaultMask: "cpf",
    category: "condutores",
    product: "auto",
    tags: ["segundo condutor", "cpf"],
    icon: "id-card",
  }),
  field({
    id: "auto.has_garage",
    name: "has_garage",
    key: "has_garage",
    label: "Possui garagem?",
    description: "Veículo guardado em garagem residencial ou estacionamento.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "veiculos",
    product: "auto",
    tags: ["garagem", "pernoite"],
    icon: "warehouse",
  }),
  field({
    id: "auto.garage_type",
    name: "garage_type",
    key: "garage_type",
    label: "Tipo de garagem",
    description: "Tipo de local de pernoite do veículo.",
    inputKind: "single_choice",
    fieldType: "SELECT",
    options: [
      { label: "Garagem fechada", value: "closed" },
      { label: "Estacionamento", value: "parking" },
      { label: "Rua", value: "street" },
    ],
    category: "veiculos",
    product: "auto",
    tags: ["garagem"],
    icon: "warehouse",
  }),
  field({
    id: "auto.had_claims",
    name: "had_claims",
    key: "had_claims",
    label: "Teve sinistro nos últimos 5 anos?",
    description: "Histórico de sinistros recentes.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "coberturas",
    product: "auto",
    tags: ["sinistro", "historico"],
    icon: "alert-triangle",
  }),
  field({
    id: "auto.claims_count",
    name: "claims_count",
    key: "claims_count",
    label: "Quantidade de sinistros",
    description: "Número de sinistros nos últimos 5 anos.",
    inputKind: "number",
    fieldType: "NUMBER",
    validation: v1({ type: "min", value: 0 }),
    category: "coberturas",
    product: "auto",
    tags: ["sinistro"],
    icon: "hash",
  }),
  field({
    id: "auto.coverage_type",
    name: "coverage_type",
    key: "coverage_type",
    label: "Tipo de cobertura",
    description: "Modalidade de cobertura desejada.",
    inputKind: "single_choice",
    fieldType: "SELECT",
    options: [
      { label: "Compreensiva", value: "comprehensive" },
      { label: "Colisão + terceiros", value: "collision_third" },
      { label: "Somente terceiros", value: "third_only" },
    ],
    category: "coberturas",
    product: "auto",
    tags: ["cobertura", "modalidade"],
    icon: "shield",
  }),
]

export const vidaFields: FieldDefinition[] = [
  field({
    id: "vida.insured_name",
    name: "insured_name",
    key: "insured_name",
    label: "Nome do segurado",
    description: "Nome completo do segurado.",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }),
    category: "dados_pessoais",
    product: "vida",
    tags: ["segurado", "vida"],
    icon: "user",
    required: true,
  }),
  field({
    id: "vida.beneficiary_name",
    name: "beneficiary_name",
    key: "beneficiary_name",
    label: "Nome do beneficiário",
    description: "Beneficiário principal da apólice.",
    inputKind: "short_text",
    fieldType: "TEXT",
    category: "beneficiarios",
    product: "vida",
    tags: ["beneficiario"],
    icon: "heart",
  }),
  field({
    id: "vida.beneficiary_relationship",
    name: "beneficiary_relationship",
    key: "beneficiary_relationship",
    label: "Parentesco",
    description: "Grau de parentesco com o segurado.",
    inputKind: "single_choice",
    fieldType: "SELECT",
    options: [
      { label: "Cônjuge", value: "spouse" },
      { label: "Filho(a)", value: "child" },
      { label: "Pai/Mãe", value: "parent" },
      { label: "Outro", value: "other" },
    ],
    category: "beneficiarios",
    product: "vida",
    tags: ["beneficiario", "parentesco"],
    icon: "users",
  }),
  field({
    id: "vida.monthly_income",
    name: "monthly_income",
    key: "monthly_income",
    label: "Renda mensal",
    description: "Renda mensal declarada.",
    inputKind: "currency",
    fieldType: "CURRENCY",
    category: "financeiro",
    product: "vida",
    tags: ["renda", "financeiro"],
    icon: "credit-card",
  }),
  field({
    id: "vida.has_health_conditions",
    name: "has_health_conditions",
    key: "has_health_conditions",
    label: "Possui condição de saúde pré-existente?",
    description: "Indica doenças ou condições relevantes.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "dados_pessoais",
    product: "vida",
    tags: ["saude"],
    icon: "heart-pulse",
  }),
  field({
    id: "vida.health_details",
    name: "health_details",
    key: "health_details",
    label: "Detalhes de saúde",
    description: "Descreva condições de saúde relevantes.",
    inputKind: "long_text",
    fieldType: "TEXTAREA",
    category: "dados_pessoais",
    product: "vida",
    tags: ["saude"],
    icon: "heart-pulse",
  }),
  field({
    id: "vida.smoker",
    name: "smoker",
    key: "smoker",
    label: "Fumante?",
    description: "Hábito de fumar nos últimos 12 meses.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "dados_pessoais",
    product: "vida",
    tags: ["habitos", "fumante"],
    icon: "cigarette",
  }),
  field({
    id: "vida.occupation",
    name: "occupation",
    key: "occupation",
    label: "Profissão",
    description: "Ocupação principal do segurado.",
    inputKind: "short_text",
    fieldType: "TEXT",
    category: "dados_pessoais",
    product: "vida",
    tags: ["profissao"],
    icon: "briefcase",
  }),
]

export const residencialFields: FieldDefinition[] = [
  field({
    id: "res.property_type",
    name: "property_type",
    key: "property_type",
    label: "Tipo de imóvel",
    description: "Classificação do imóvel segurado.",
    inputKind: "single_choice",
    fieldType: "SELECT",
    options: [
      { label: "Casa", value: "house" },
      { label: "Apartamento", value: "apartment" },
      { label: "Sobrado", value: "townhouse" },
    ],
    category: "imovel",
    product: "residencial",
    tags: ["imovel", "tipo"],
    icon: "home",
  }),
  field({
    id: "res.construction_type",
    name: "construction_type",
    key: "construction_type",
    label: "Tipo de construção",
    description: "Material predominante da construção.",
    inputKind: "single_choice",
    fieldType: "SELECT",
    options: [
      { label: "Alvenaria", value: "masonry" },
      { label: "Madeira", value: "wood" },
      { label: "Mista", value: "mixed" },
    ],
    category: "imovel",
    product: "residencial",
    tags: ["construcao"],
    icon: "building",
  }),
  field({
    id: "res.property_value",
    name: "property_value",
    key: "property_value",
    label: "Valor do imóvel",
    description: "Valor estimado do imóvel.",
    inputKind: "currency",
    fieldType: "CURRENCY",
    category: "financeiro",
    product: "residencial",
    tags: ["valor", "imovel"],
    icon: "credit-card",
  }),
  field({
    id: "res.contents_value",
    name: "contents_value",
    key: "contents_value",
    label: "Valor do conteúdo",
    description: "Valor estimado do conteúdo interno.",
    inputKind: "currency",
    fieldType: "CURRENCY",
    category: "financeiro",
    product: "residencial",
    tags: ["conteudo"],
    icon: "package",
  }),
  field({
    id: "res.has_alarm",
    name: "has_alarm",
    key: "has_alarm",
    label: "Possui alarme?",
    description: "Sistema de alarme instalado.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "imovel",
    product: "residencial",
    tags: ["seguranca", "alarme"],
    icon: "shield",
  }),
  field({
    id: "res.has_cameras",
    name: "has_cameras",
    key: "has_cameras",
    label: "Possui câmeras?",
    description: "Circuito de monitoramento por câmeras.",
    inputKind: "yes_no",
    fieldType: "BOOLEAN",
    category: "imovel",
    product: "residencial",
    tags: ["seguranca", "cameras"],
    icon: "video",
  }),
]

export const empresarialFields: FieldDefinition[] = [
  field({
    id: "biz.company_name",
    name: "company_name",
    key: "company_name",
    label: "Razão social",
    description: "Nome empresarial da organização.",
    inputKind: "short_text",
    fieldType: "TEXT",
    validation: v1({ type: "required", when: "finalize" }),
    category: "empresa",
    product: "empresarial",
    tags: ["empresa", "razao social"],
    icon: "building",
    required: true,
  }),
  field({
    id: "biz.employee_count",
    name: "employee_count",
    key: "employee_count",
    label: "Número de funcionários",
    description: "Quantidade de colaboradores.",
    inputKind: "number",
    fieldType: "NUMBER",
    validation: v1({ type: "min", value: 0 }),
    category: "empresa",
    product: "empresarial",
    tags: ["funcionarios", "rh"],
    icon: "users",
  }),
  field({
    id: "biz.annual_revenue",
    name: "annual_revenue",
    key: "annual_revenue",
    label: "Faturamento anual",
    description: "Receita bruta anual estimada.",
    inputKind: "currency",
    fieldType: "CURRENCY",
    category: "financeiro",
    product: "empresarial",
    tags: ["faturamento", "financeiro"],
    icon: "credit-card",
  }),
  field({
    id: "biz.business_activity",
    name: "business_activity",
    key: "business_activity",
    label: "Ramo de atividade",
    description: "Atividade principal da empresa.",
    inputKind: "short_text",
    fieldType: "TEXT",
    category: "empresa",
    product: "empresarial",
    tags: ["atividade", "ramo"],
    icon: "briefcase",
  }),
  field({
    id: "biz.equipment_value",
    name: "equipment_value",
    key: "equipment_value",
    label: "Valor dos equipamentos",
    description: "Valor total dos equipamentos a segurar.",
    inputKind: "currency",
    fieldType: "CURRENCY",
    category: "empresa",
    product: "empresarial",
    tags: ["equipamentos"],
    icon: "wrench",
  }),
  field({
    id: "biz.equipment_list",
    name: "equipment_list",
    key: "equipment_list",
    label: "Lista de equipamentos",
    description: "Descrição dos principais equipamentos.",
    inputKind: "long_text",
    fieldType: "TEXTAREA",
    category: "empresa",
    product: "empresarial",
    tags: ["equipamentos"],
    icon: "list",
  }),
]

export const allCatalogFields: FieldDefinition[] = [
  ...sharedFields,
  ...autoFields,
  ...vidaFields,
  ...residencialFields,
  ...empresarialFields,
]

export const fieldCatalogById = new Map(
  allCatalogFields.map((item) => [item.id, item]),
)

export function getFieldDefinition(id: string): FieldDefinition | undefined {
  return fieldCatalogById.get(id)
}
